### PR TITLE
Added different NPC#setSkin methods and NotPlayerNPCException

### PR DESCRIPTION
**Pull request by Lichthagel**

### CODE REVIEW

**Comment by fullwall** [comment]
How does this differ from https://github.com/CitizensDev/Citizens2/blob/master/main/src/main/java/net/citizensnpcs/npc/skin/SkinnableEntity.java? I'd rather move that interface across as a Trait than do these per-type methods.

**Comment by Lichthagel** [comment]
It makes Things much easier and has not only a username/uuid as Parameter.

**Comment by fullwall** [comment]
I like the idea behind this pull request but Player-specific methods should not be on NPC, they should be on a trait like most other entity type specific methods.

**Comment by Lichthagel** [comment]
Then why not make a PlayerNPC class?

**Comment by fullwall** [comment]
https://github.com/CitizensDev/Citizens2/blob/master/v1_10_R1/src/main/java/net/citizensnpcs/nms/v1_10_R1/entity/EntityHumanNPC.java#L399
https://github.com/CitizensDev/Citizens2/blob/master/main/src/main/java/net/citizensnpcs/trait/SheepTrait.java
Some examples of how it has been implemented previously

**Comment by Lichthagel** [comment]
Well this is really awful

**Comment by fullwall** [comment]
I can implement this API the Citizens way if you'd like.

**Comment by Lichthagel** [comment]
Well it would be easy if i could just cast an npc to their corresponding PlayerNPC etc.

**Comment by fullwall** [comment]
You can cast a getEntity() directly into a SkinnableEntity - because of the recent refactoring I did to allow for multi-version control there's no similar concept for players yet but I could add that.

**Comment by Lichthagel** [comment]
Would be nice and easy.

**Pull request closed without merging**
