### PR TITLE
fix: make similar events use same listener list

### PR DESCRIPTION
**Pull request by SNWCreations**
just like what Bukkit does, they share a listener list between similar damage events.

### CODE REVIEW

**Comment by fullwall** [comment]
I don't think we should do this change, because it's not backwards compatible.

**Comment by SNWCreations** [comment]
you're right but it may force devs use different delegate methods subscribing to subclasses for a simple logic based on the base event class.
any other solutions?

**Comment by fullwall** [comment]
I don't think this is a big issue, I wouldn't spend any time on it. More important things to do first

**Comment by SNWCreations** [comment]
Yeah fine. I'll leave the branch there. Hope we could talk about it someday in the future.

**Pull request closed without merging**
